BracketTracker/Models/Round.cs
using System.Collections.Generic;

namespace BracketTracker.Models
{
    public class Round
    {
        public int RoundId { get; set; }
        public bool Result { get; set; }
        public List<TeamRound> JoinEntities { get; set; }
    }
}

BracketTracker/Controllers/RoundsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using BracketTracker.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace BracketTracker.Controllers
{
  public class RoundsController : Controller
  {
    private readonly BracketTrackerContext _db;
    public RoundsController(BracketTrackerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      ViewBag.winnerBracket = _db.Winners.ToList();
      ViewBag.loserBracket = _db.Losers.ToList();
      ViewBag.allTeamRounds = _db.TeamRounds.ToList();
      List<Round> rounds = _db.Rounds.Include(round => round.JoinEntities)
                                      .ThenInclude(join => join.Team)
                                      .ToList();
      return View(rounds);
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.TeamId = new SelectList(_db.Teams, "TeamId", "Name");
      return View();
    }

    [Authorize]
    [HttpPost]
    public ActionResult Create(Round round, int[] TeamId)
    {
      _db.Rounds.Add(round);
      _db.SaveChanges();
      Team team1 = _db.Teams.FirstOrDefault(team => team.TeamId == TeamId[0]);
      Team team2 = _db.Teams.FirstOrDefault(team => team.TeamId == TeamId[1]);
      if (round.Result == false)
      {
        team1.Losses++;
        team2.Wins++;
        _db.Teams.Update(team1);
        _db.Teams.Update(team2);
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[0], Outcome = false });
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[1], Outcome = true });
        Winner winner = (new Winner() { TeamId = team2.TeamId });
        _db.Winners.Add(winner);
        _db.SaveChanges();
      }
      else
      {
        team1.Wins++;
        team2.Losses++;
        _db.Teams.Update(team1);
        _db.Teams.Update(team2);
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[0], Outcome = true });
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[1], Outcome = false });
        Winner winner = (new Winner() { TeamId = team1.TeamId });
        _db.Winners.Add(winner);
        _db.SaveChanges();
      }
      if (team1.Losses >= 2)
      {
#nullable enable
        Winner? winner = _db.Winners.FirstOrDefault(win => win.TeamId == team1.TeamId);
#nullable disable
        if (winner == null)
        {
          Loser loser = (new Loser() { TeamId = team1.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
      }
      if (team2.Losses >= 2)
      {
#nullable enable
        Winner? winner = _db.Winners.FirstOrDefault(win => win.TeamId == team2.TeamId);
#nullable disable
        if (winner == null)
        {
          Loser loser = (new Loser() { TeamId = team2.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
      }
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Play()
    {
      ViewBag.TeamId = new SelectList(_db.Teams, "TeamId", "Name");
      return View();
    }

    [Authorize]
    [HttpPost]
    public ActionResult Play(Round round, int[] TeamId)
    {
      Random randy = new Random();
      if (randy.Next(2) == 0)
      {
        //Team 1 Loss, Team 2 Win
        round.Result = false;
      }
      else
      {
        //Team 1 Win, Team 2 Loss
        round.Result = true;
      }
      _db.Rounds.Add(round);
      _db.SaveChanges();

      //Determines which team was in which team slot (team 1 outcome: true = win, false = loss)
      Team team1 = _db.Teams.FirstOrDefault(team => team.TeamId == TeamId[0]);
      Team team2 = _db.Teams.FirstOrDefault(team => team.TeamId == TeamId[1]);

      if (round.Result == false)
      {
        team1.Losses++;
        team2.Wins++;

        if (team1.Losses >= 2)
        {
          Loser loser = _db.Losers.FirstOrDefault(lsr => lsr.TeamId == team1.TeamId);
          _db.Losers.Remove(loser);
        }

        _db.Teams.Update(team1);
        _db.Teams.Update(team2);
        _db.SaveChanges();

        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[0], Outcome = false });
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[1], Outcome = true });
        _db.SaveChanges();

        //Loser added to Loser bracket
#nullable enable
        Winner? bracketLwr = _db.Winners.FirstOrDefault(win => win.TeamId == team1.TeamId);
#nullable disable

        if (bracketLwr == null && team1.Losses == 1)
        {
          Loser loser = (new Loser() { TeamId = team1.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
        else
        {
          _db.Winners.Remove(bracketLwr);
          Loser loser = (new Loser() { TeamId = team1.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }

        //Winner added to Winner bracket
#nullable enable
        Winner? actualWinner = _db.Winners.FirstOrDefault(win => win.TeamId == team1.TeamId);
#nullable disable
        if (actualWinner == null)
        {
          Winner roundWinner = (new Winner() { TeamId = team2.TeamId });
          _db.Winners.Add(roundWinner);
          _db.SaveChanges();
        }
      }
      else
      {
        team1.Wins++;
        team2.Losses++;

        //Loser kicked out of Loser bracket and tournament
        if (team2.Losses >= 2)
        {
          Loser loser = _db.Losers.FirstOrDefault(lsr => lsr.TeamId == team2.TeamId);
          _db.Losers.Remove(loser);
        }
        _db.SaveChanges();
        _db.Teams.Update(team1);
        _db.Teams.Update(team2);

        _db.SaveChanges();
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[0], Outcome = true });
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[1], Outcome = false });
        _db.SaveChanges();

        //Loser with no previous losses going to Loser bracket
#nullable enable
        Winner? bracketLwr = _db.Winners.FirstOrDefault(win => win.TeamId == team2.TeamId);
#nullable disable
        if (bracketLwr == null && team2.Losses == 1)
        {
          Loser loser = (new Loser() { TeamId = team2.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
        //Winner with 1 previous loss going to Loser bracket
        else
        {
          // #nullable enable
          //                 Winner? bracketLwr = _db.Winners.FirstOrDefault(win => win.TeamId == team2.TeamId);
          // #nullable disable
          _db.Winners.Remove(bracketLwr);
          Loser loser = (new Loser() { TeamId = team2.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
        //Winner with first win to Winners bracket
#nullable enable
        Winner? actualWinner = _db.Winners.FirstOrDefault(win => win.TeamId == team1.TeamId);
#nullable disable
        if (actualWinner == null)
        {
          Winner roundWinner = (new Winner() { TeamId = team1.TeamId });
          _db.Winners.Add(roundWinner);
          _db.SaveChanges();
        }

      }

      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Round thisRound = _db.Rounds

            .Include(round => round.JoinEntities)
            .ThenInclude(join => join.Team)
            .FirstOrDefault(round => round.RoundId == id);
      return View(thisRound);
    }


    [Authorize]
    public ActionResult Delete(int id)
    {
      Round thisRound = _db.Rounds.FirstOrDefault(rounds => rounds.RoundId == id);
      return View(thisRound);
    }

    [Authorize]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Round thisRound = _db.Rounds.FirstOrDefault(rounds => rounds.RoundId == id);
      _db.Rounds.Remove(thisRound);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BracketTracker/Controllers/TeamsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BracketTracker.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace BracketTracker.Controllers;

public class TeamsController : Controller
{
  private readonly BracketTrackerContext _db;
  private readonly UserManager<ApplicationUser> _userManager;

  public TeamsController(UserManager<ApplicationUser> userManager, BracketTrackerContext db)
  {
    _userManager = userManager;
    _db = db;
  }


  public async Task<ActionResult> Index()
  {
    var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
    var teams = new DatabaseInfo {
      AllTeams = _db.Teams
                  .Include(player => player.Players)
                  .Include(teamround => teamround.JoinEntities)
                  .ThenInclude(round => round.Round),
    };
    if (currentUser != null)
    {
      teams.MyTeams = _db.Teams
                            .Where(entry => entry.User.Id == currentUser.Id)
                            .Include(player => player.Players)
                            .Include(teamround => teamround.JoinEntities)
                            .ThenInclude(round => round.Round);
    }
    return View(teams);
  }

  [Authorize]
  public ActionResult Create()
  {
    return View();
  }

  [Authorize]
  [HttpPost]
  public async Task<ActionResult> Create(Team team)
  {
    if (!ModelState.IsValid)
    {
      return View(team);
    }
    else
    {
      var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
      team.User = currentUser;
      _db.Teams.Add(team);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }



  public ActionResult Details(int id)
  {
    var thisTeam = _db.Teams
          .Include(team => team.JoinEntities)
          .ThenInclude(join => join.Round)
          .Include(playerTeam => playerTeam.PlayerTeams)
          .ThenInclude(player => player.Player)
          .FirstOrDefault(team => team.TeamId == id);
    return View(thisTeam);
  }

  public async Task<ActionResult> MyTeam()
  {
    var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
    ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
    var userTeams = new DatabaseInfo {
      MyTeams = _db.Teams
                    .Where(e =>e.User.Id == currentUser.Id)
                    .Include(player => player.Players)
                    .Include(teamround => teamround.JoinEntities)
                    .ThenInclude(round => round.Round)
    };
    return View(userTeams);
  }

  [Authorize]
  public ActionResult Delete(int id)
  {
    Team thisTeam = _db.Teams.FirstOrDefault(teams => teams.TeamId == id);
    return View(thisTeam);
  }

  [Authorize]
  [HttpPost, ActionName("Delete")]
  public ActionResult DeleteConfirmed(int id)
  {
    Team thisTeam = _db.Teams.FirstOrDefault(teams => teams.TeamId == id);
    _db.Teams.Remove(thisTeam);
    _db.SaveChanges();
    return RedirectToAction("Index");
  }
}

BracketTracker/Views/Rounds/Create.cshtml
@{
  Layout = "_Layout";
}

@model BracketTracker.Models.Round

<h2>Determine Players in Round- and Outcome!</h2>

<h4>Add Teams to this Round: </h4>
<h4>Toggle the Circle Button to enter the winner</h4>
<br>
@using (Html.BeginForm())
{
    <label>Team One: </label>
    @Html.DropDownList("TeamId")
    <span> Toggle button to indicate that this team won: </span>@Html.RadioButtonFor(model => model.Result, "true")
    <br>
    <br>
    <label>Team Two: </label>
    @Html.DropDownList("TeamId")
    <span> Toggle button to indicate that this team won: </span>@Html.RadioButtonFor(model => model.Result, "false")
    <br>
    <br>
    <input type="submit" value="Add Round Result">
}
<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("See all Rounds completed this session", "Index")</p>
<p>@Html.ActionLink("See all Teams", "Index", "Teams")</p>

BracketTracker/Views/Rounds/Delete.cshtml
@{
    Layout = "_Layout";
}


@model BracketTracker.Models.Round

<h2>Delete this Round?</h2>
<hr />
@Html.DisplayNameFor(model => model.RoundId): @Html.DisplayFor(model => model.RoundId)
@using (Html.BeginForm())
{
    @Html.Hidden("RoundId", @Model.RoundId)
    <input type="submit" value="Delete" />
}

<hr />
<p>@Html.ActionLink("Back to Rounds", "Index")</p>
<p>@Html.ActionLink("Back to Details", "Details", new { id = @Model.RoundId});</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

BracketTracker/Views/Rounds/Details.cshtml
@{
	Layout = "_Layout";
}

@using BracketTracker.Models
@model BracketTracker.Models.Round

<h2>Round Record:</h2>
<hr />

<h3><label>Round</label>: @Html.DisplayFor(model =>model.RoundId)</h3>

@if (@Model.JoinEntities.Count == 0)
{
	<p>No Rounds in this Session. Make some Teams!</p>
	@Html.ActionLink("Teams some Make", "Create", "Teams")
}
else
{
	<p>Teams in this Round:</p>
	<ul>
	@if (@Model.JoinEntities.Count == 0)
		{
			<p>This Round had no teams...? Blasphemy!</p>
		}
		else
		{
			@foreach (TeamRound teamRound in Model.JoinEntities)
			{
				<li>Team: @teamRound.Team.Name | @if (teamRound.Outcome == false)
					{
						<span>Lost</span>;
					}
					else
					{
						<span>Won</span>
					}
				</li>
			}
		}
	</ul>
}

<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("Back to Teams", "Index")</p>
<p>@Html.ActionLink("See all completed Rounds this Session", "Index", "Rounds")</p>
<p>@Html.ActionLink("Delete this Round?", "Delete", new { id = Model.RoundId})</p>

BracketTracker/Views/Rounds/Index.cshtml
@{
  Layout = "_Layout";
  List<TeamRound> teamRounds = ViewBag.allTeamRounds;
  List<Winner> WinnerBracket = ViewBag.winnerBracket;
  List<Loser> LoserBracket = ViewBag.loserBracket;
}

<h2>SHOW ME SOME ROUNDS, BOY</h2>
<hr />

@using BracketTracker.Models

<div class="columns"> 
@if (Model.Count == 0)
{
  <p>No rounds yet</p>
}
<ol>
  @foreach (Round round in Model)
  {
    <li>@Html.ActionLink($"Round {round.RoundId}", "Details", new { id = round.RoundId})
      @foreach (TeamRound teamRound in teamRounds)
      {
        @if (round.RoundId == teamRound.RoundId)
        {
          @if (teamRound.Outcome == true)
          {
            @if (teamRound.Team.Name != "")
            {
              <p>Winner: @teamRound.Team.Name</p>
            }
          }
          else
          {
              <p>Loser: @teamRound.Team.Name</p>
          }
        }
      }
      </li>
  }
</ol>
</div>
<div class="columns winners">
  <h1>Winners Bracket</h1>
  @if (WinnerBracket.Count == 0)
  {
    <p>No one has played yet.</p>
  }
  else
  {
    @foreach (Winner winner in WinnerBracket)
    {
      <p>@winner.Team.Name</p>
    }
  }
</div>
<div class="columns losers">
  <h1>Losers Bracket</h1>
  @if (LoserBracket.Count == 0)
  {
    <p>No one has lost yet.</p>
  }
  else
  {
    @foreach (Loser loser in LoserBracket)
    {
      <p>@loser.Team.Name</p>
    }
  }
</div>
<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("See all Teams", "Index", "Teams")</p>
<p>@Html.ActionLink("New Round, Same Session?", "Create")</p>
<p>@Html.ActionLink("Add more Teams", "Create", "Teams")</p>

BracketTracker/Views/Rounds/Play.cshtml
@{
	Layout = "_Layout";
}

@model BracketTracker.Models.Round

<h2>Determine Players in Round- and Outcome!</h2>

<h4>Add Teams to this Round: </h4>
<h4>Press the Button to Play a Random Round</h4>
<br>
@using (Html.BeginForm())
{
	<label>Team One: </label>
	@Html.DropDownList("TeamId") <span>   </span>
	<label>Team Two: </label>
	@Html.DropDownList("TeamId")

	<br>
	<br>
	<input type="submit" value="Place Your Bets!">
}
<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("See all Rounds completed this session", "Index")</p>
<p>@Html.ActionLink("See all Teams", "Index", "Teams")</p>