BracketTracker/Models/Player.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace BracketTracker.Models;

public class Player
{
  public int PlayerId { get; set; }
  public string Name { get; set; }
  public int Powerscore { get; set; }
  public Team Team { get; set; }
  public List<PlayerTeam> PlayerTeams { get; set; }
  // public int Cost { get; set; }
}

BracketTracker/Controllers/PlayersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using BracketTracker.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace BracketTracker.Controllers
{
  public class PlayersController : Controller
  {
    private readonly BracketTrackerContext _db;
    public PlayersController(BracketTrackerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Players.ToList());
    }

    public ActionResult Details(int id)
    {
      Player thisPlayer = _db.Players
                              .Include(pt => pt.PlayerTeams)
                              .ThenInclude(team => team.Team)
                              .FirstOrDefault(player => player.PlayerId == id);
      return View(thisPlayer);
    }

    // all below to be required by Admin Authorization
    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [Authorize]
    [HttpPost]
    public ActionResult Create(Player player)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }
      else
      {
        _db.Players.Add(player);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    [Authorize]
    public ActionResult Delete(int id)
    {
      Player thisPlayer = _db.Players.FirstOrDefault(player => player.PlayerId == id);
      return View(thisPlayer);
    }

    [Authorize]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Player thisPlayer = _db.Players.FirstOrDefault(player => player.PlayerId == id);
      _db.Players.Remove(thisPlayer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
      Player thisPlayer = _db.Players.FirstOrDefault(player => player.PlayerId == id);
      return View(thisPlayer);
    }

    [Authorize]
    [HttpPost]
    public ActionResult Edit(Player player)
    {
      _db.Players.Update(player);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AssignPlayer(int teamId)
    {
      ViewBag.PlayersList = _db.Players.ToList();
      ViewBag.TeamId = teamId;
      ViewBag.PlayerId = new SelectList(_db.Players, "PlayerId", "Name");
      return View();
    }

    [Authorize]
    [HttpPost]
    public ActionResult AssignPlayer(Player player, int teamId)
    {
      #nullable enable
      PlayerTeam? joinEntity = _db.PlayerTeams.FirstOrDefault(join => (join.TeamId == teamId && join.PlayerId == player.PlayerId));
      #nullable disable
      if (joinEntity == null && teamId !=0)
      {
        _db.PlayerTeams.Add(new PlayerTeam() { TeamId = teamId, PlayerId = player.PlayerId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", "Teams", new { id = teamId });
    }
  }
}

BracketTracker/Controllers/RoundsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using BracketTracker.Models;
using System.Collections.Generic;
using System.Linq;
using System;

namespace BracketTracker.Controllers
{
  public class RoundsController : Controller
  {
    private readonly BracketTrackerContext _db;
    public RoundsController(BracketTrackerContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      ViewBag.winnerBracket = _db.Winners.ToList();
      ViewBag.loserBracket = _db.Losers.ToList();
      ViewBag.allTeamRounds = _db.TeamRounds.ToList();
      List<Round> rounds = _db.Rounds.Include(round => round.JoinEntities)
                                      .ThenInclude(join => join.Team)
                                      .ToList();
      return View(rounds);
    }

    [Authorize]
    public ActionResult Create()
    {
      ViewBag.TeamId = new SelectList(_db.Teams, "TeamId", "Name");
      return View();
    }

    [Authorize]
    [HttpPost]
    public ActionResult Create(Round round, int[] TeamId)
    {
      _db.Rounds.Add(round);
      _db.SaveChanges();
      Team team1 = _db.Teams.FirstOrDefault(team => team.TeamId == TeamId[0]);
      Team team2 = _db.Teams.FirstOrDefault(team => team.TeamId == TeamId[1]);
      if (round.Result == false)
      {
        team1.Losses++;
        team2.Wins++;
        _db.Teams.Update(team1);
        _db.Teams.Update(team2);
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[0], Outcome = false });
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[1], Outcome = true });
        Winner winner = (new Winner() { TeamId = team2.TeamId });
        _db.Winners.Add(winner);
        _db.SaveChanges();
      }
      else
      {
        team1.Wins++;
        team2.Losses++;
        _db.Teams.Update(team1);
        _db.Teams.Update(team2);
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[0], Outcome = true });
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[1], Outcome = false });
        Winner winner = (new Winner() { TeamId = team1.TeamId });
        _db.Winners.Add(winner);
        _db.SaveChanges();
      }
      if (team1.Losses >= 2)
      {
#nullable enable
        Winner? winner = _db.Winners.FirstOrDefault(win => win.TeamId == team1.TeamId);
#nullable disable
        if (winner == null)
        {
          Loser loser = (new Loser() { TeamId = team1.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
      }
      if (team2.Losses >= 2)
      {
#nullable enable
        Winner? winner = _db.Winners.FirstOrDefault(win => win.TeamId == team2.TeamId);
#nullable disable
        if (winner == null)
        {
          Loser loser = (new Loser() { TeamId = team2.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
      }
      return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult Play()
    {
      ViewBag.TeamId = new SelectList(_db.Teams, "TeamId", "Name");
      return View();
    }

    [Authorize]
    [HttpPost]
    public ActionResult Play(Round round, int[] TeamId)
    {
      Random randy = new Random();
      if (randy.Next(2) == 0)
      {
        //Team 1 Loss, Team 2 Win
        round.Result = false;
      }
      else
      {
        //Team 1 Win, Team 2 Loss
        round.Result = true;
      }
      _db.Rounds.Add(round);
      _db.SaveChanges();

      //Determines which team was in which team slot (team 1 outcome: true = win, false = loss)
      Team team1 = _db.Teams.FirstOrDefault(team => team.TeamId == TeamId[0]);
      Team team2 = _db.Teams.FirstOrDefault(team => team.TeamId == TeamId[1]);

      if (round.Result == false)
      {
        team1.Losses++;
        team2.Wins++;

        if (team1.Losses >= 2)
        {
          Loser loser = _db.Losers.FirstOrDefault(lsr => lsr.TeamId == team1.TeamId);
          _db.Losers.Remove(loser);
        }

        _db.Teams.Update(team1);
        _db.Teams.Update(team2);
        _db.SaveChanges();

        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[0], Outcome = false });
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[1], Outcome = true });
        _db.SaveChanges();

        //Loser added to Loser bracket
#nullable enable
        Winner? bracketLwr = _db.Winners.FirstOrDefault(win => win.TeamId == team1.TeamId);
#nullable disable

        if (bracketLwr == null && team1.Losses == 1)
        {
          Loser loser = (new Loser() { TeamId = team1.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
        else
        {
          _db.Winners.Remove(bracketLwr);
          Loser loser = (new Loser() { TeamId = team1.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }

        //Winner added to Winner bracket
#nullable enable
        Winner? actualWinner = _db.Winners.FirstOrDefault(win => win.TeamId == team1.TeamId);
#nullable disable
        if (actualWinner == null)
        {
          Winner roundWinner = (new Winner() { TeamId = team2.TeamId });
          _db.Winners.Add(roundWinner);
          _db.SaveChanges();
        }
      }
      else
      {
        team1.Wins++;
        team2.Losses++;

        //Loser kicked out of Loser bracket and tournament
        if (team2.Losses >= 2)
        {
          Loser loser = _db.Losers.FirstOrDefault(lsr => lsr.TeamId == team2.TeamId);
          _db.Losers.Remove(loser);
        }
        _db.SaveChanges();
        _db.Teams.Update(team1);
        _db.Teams.Update(team2);

        _db.SaveChanges();
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[0], Outcome = true });
        _db.TeamRounds.Add(new TeamRound() { RoundId = round.RoundId, TeamId = TeamId[1], Outcome = false });
        _db.SaveChanges();

        //Loser with no previous losses going to Loser bracket
#nullable enable
        Winner? bracketLwr = _db.Winners.FirstOrDefault(win => win.TeamId == team2.TeamId);
#nullable disable
        if (bracketLwr == null && team2.Losses == 1)
        {
          Loser loser = (new Loser() { TeamId = team2.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
        //Winner with 1 previous loss going to Loser bracket
        else
        {
          // #nullable enable
          //                 Winner? bracketLwr = _db.Winners.FirstOrDefault(win => win.TeamId == team2.TeamId);
          // #nullable disable
          _db.Winners.Remove(bracketLwr);
          Loser loser = (new Loser() { TeamId = team2.TeamId });
          _db.Losers.Add(loser);
          _db.SaveChanges();
        }
        //Winner with first win to Winners bracket
#nullable enable
        Winner? actualWinner = _db.Winners.FirstOrDefault(win => win.TeamId == team1.TeamId);
#nullable disable
        if (actualWinner == null)
        {
          Winner roundWinner = (new Winner() { TeamId = team1.TeamId });
          _db.Winners.Add(roundWinner);
          _db.SaveChanges();
        }

      }

      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Round thisRound = _db.Rounds

            .Include(round => round.JoinEntities)
            .ThenInclude(join => join.Team)
            .FirstOrDefault(round => round.RoundId == id);
      return View(thisRound);
    }


    [Authorize]
    public ActionResult Delete(int id)
    {
      Round thisRound = _db.Rounds.FirstOrDefault(rounds => rounds.RoundId == id);
      return View(thisRound);
    }

    [Authorize]
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Round thisRound = _db.Rounds.FirstOrDefault(rounds => rounds.RoundId == id);
      _db.Rounds.Remove(thisRound);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

BracketTracker/Views/Players/AssignPlayer.cshtml
@{
  Layout = "_Layout";
}

@using BracketTracker.Models
@model BracketTracker.Models.Player

<h2>Assign a Player</h2>

<h4>Assign a player to this team: @Html.DisplayFor(model => model.Name)</h4>

@if (@ViewBag.PlayersList.Count == 0)
{
  <p>You must create some players first!</p>
  <p>@Html.ActionLink("Assign a player", "Create", "Players")</p>
}
else
{
  <ul>
  @foreach (Player player in ViewBag.PlayersList)
    {
      <li>@nameof(player.Name): @player.Name</li>
      <ul>
        <li>@nameof(player.Powerscore): @player.Powerscore</li>
      </ul>
    }
  </ul>
  @using (Html.BeginForm())
  {
    @* @Html.HiddenFor(model => model.TeamId)
    @Html.HiddenFor(model => model.Name)
    @Html.HiddenFor(model => model.Powerscore) *@
    <input class="hidden" value=@ViewBag.TeamId name="teamId"/>

    @Html.Label("Select Player")
    @Html.DropDownList("PlayerId")

    <input type="submit" value="Assign player to my team" class="btn btn-default" />
  }
}
<p>@Html.ActionLink("return home", "Index", "Home")</p>
<P>@Html.ActionLink("Create Players", "Create")</P>

BracketTracker/Views/Players/Create.cshtml
@{
  Layout = "_Layout";
}

@model BracketTracker.Models.Player

<h2>Add a Player</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>
@using (Html.BeginForm())
{
  <p>@Html.LabelFor(model => model.Name): @Html.TextBoxFor(model => model.Name)</p>
  <p>@Html.LabelFor(model => model.Powerscore): @Html.TextBoxFor(model => model.Powerscore, new { type="number", min="1", max="10"})</p>
  <input type="submit" value="Add Player">
}
<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("See all Players", "Index")</p>

BracketTracker/Views/Players/Delete.cshtml
@{
    Layout = "_Layout";
}


@model BracketTracker.Models.Player

<h2>Delete this Player?</h2>
<hr />
@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    @Html.Hidden("playerId", @Model.PlayerId)
    <input type="submit" value="Delete" />
}

<hr />
<p>@Html.ActionLink("Back to Players", "Index")</p>
<p>@Html.ActionLink("Back to Details", "Details", new { id = @Model.PlayerId});</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

BracketTracker/Views/Players/Details.cshtml
@{
	Layout = "_Layout";
}

@using BracketTracker.Models
@model BracketTracker.Models.Player

<h2>Player Record:</h2>
<hr />

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model =>model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Powerscore): @Html.DisplayFor(model => model.Powerscore)</h3>

@if (Model.PlayerTeams.Count == 0)
{
	<p>This player has no Team on record</p>
	@Html.ActionLink("Add this player to a team", "AssignPlayer")
}
else
{
	@foreach (var pt in Model.PlayerTeams)
	{
		<h5>Team Assignment: @pt.Team.Name </h5>
	}
}


@* @if (@Model.JoinEntities.Count == 0)
{
<p>This team has no record. Put 'em in, coach!</p>
@Html.ActionLink("And by that, I mean put them in a round", "Create", "Rounds")
}
else
{
<p>Involved in Rounds:</p>
<ul>
@if (@Model.JoinEntities.Count == 0)
{
<p>This team has no record!</p>
}
else
{
@foreach (TeamRound teamRound in Model.JoinEntities)
{
<li>Round @teamRound.RoundId | @if (teamRound.Outcome == false)
{
<span>Lost</span>;
}
else
{
<span>Won</span>
}
</li>
}
}
</ul>
}

<p>Team Wins: @Model.Wins</p>
<p>Team Losses: @Model.Losses</p> *@

<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("Back to Teams", "Index", "Teams")</p>
<p>@Html.ActionLink("See all completed Rounds this Session", "Index", "Rounds")</p>
<p>@Html.ActionLink("Delete this Player?", "Delete", new { id = Model.PlayerId})</p>

BracketTracker/Views/Players/Edit.cshtml
@{
    Layout = "_Layout";
}


@model BracketTracker.Models.Player

<h2>Edit this Player?</h2>
<hr />
@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    @Html.Hidden("playerId", @Model.PlayerId)
    @Html.EditorFor(model => model.Powerscore)
    @Html.EditorFor(model => model.Name)
    <input type="submit" value="Update" />
}

<hr />
<p>@Html.ActionLink("Back to Players", "Index")</p>
<p>@Html.ActionLink("Back to Details", "Details", new { id = @Model.PlayerId});</p>
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>

BracketTracker/Views/Players/Index.cshtml
@{
  Layout = "_Layout";
}

@using BracketTracker.Models

<h2>Player Pool!</h2>

@if (Model.Count == 0)
{
  <p>No players yet</p>
}

<ul>
@foreach (Player player in Model)
{
  <li>@Html.ActionLink($"{player.Name}", "Details", new { id = player.PlayerId })</li>
}
</ul>
<hr />
<p>@Html.ActionLink("Back to Home", "Index", "Home")</p>
<p>@Html.ActionLink("Add another Player", "Create")</p>
@* <p>@Html.ActionLink("Delete a Player", "Delete")</p> *@
<p>@Html.ActionLink("See all completed Rounds this session", "Index", "Rounds")</p>